### ISSUE TITLE
NotADirectoryError for /binwalk/magic

### ISSUE THREAD

**Issue by Timonheu** [OSPG/binwalk#19]
I am running binwalk in a docker container which runs Debian 12 and python 3.10.12. I installed from this repository in the dockerfile (as root) as follows:
```
RUN wget --progress=dot:giga https://github.com/OSPG/binwalk/archive/master.zip &&\
  unzip master.zip
WORKDIR ${homedir}/binwalk-master
RUN python setup.py uninstall && python setup.py install
RUN chmod +x ./deps.sh && ./deps.sh --yes
```
Subsequently running binwalk in the container through bash gives no output, Running the following minimal example in the container
```python
import binwalk

binwalk.scan()
```
gives the output:
```
Traceback (most recent call last):
  File "/home/path/to/minimal_test.py", line 3, in <module>
    binwalk.scan()
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/__init__.py", line 14, in scan
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/core/module.py", line 795, in execute
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/core/module.py", line 720, in list
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/core/settings.py", line 51, in __init__
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/core/settings.py", line 77, in _magic_signature_files
  File "/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/core/settings.py", line 70, in list_files
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.10/site-packages/binwalk-2.4.1-py3.10.egg/binwalk/magic'
```
Is there a way I can fix this installation?

**Comment by stkw0** [comment]
Could you share the complete Dockerfile? I tried to reproduce the issue with your steps but I couldn't get that error. 

The installation instructions are a bit outdated, I will update them in the next days. Have you tried creating a python virtual environment before running ./deps.sh and setup.py?

**Comment by stkw0** [comment]
I updated the installation instruction and dep.sh script with PR https://github.com/OSPG/binwalk/pull/20. I test it in a fresh debian docker container and it seems to work correctly. 

By a chance did you used `python` docker image as base? I found some issues when using that particular image that don't show up when using the standard `debian` docker image. 

Let me know the issue persist.

**Comment by Timonheu** [comment]
Thank you for your responses, and aplogogies for the lack of mine.

That would indeed be the issue, I was using the `python` base image. Thank you for the great help and thank you for maintaning this awesome tool!
